# Check the demand (v2)

Accumulate the region of the user wishes.

Uses the `UserDispo` file.


The `UsersDispo` file has the same shape as the others, example:

```
6/8/2026  0:0:0  0:0:0  0:0:0  0:0:0  ---------- 0 0
R	86400 1784073600 0 0 0
N	YES:Faure
6/8/2026  0:0:0  0:0:0  0:0:0  0:0:0  ---------- 0 0
R	86400 1781395200 0 0 0
N	YES:Mattsn
```

But may be full of errors with missing `R` lines ...

In [ ]:
%matplotlib widget
# from datetime import datetime
# import numpy as np
from matplotlib.pyplot import subplots

# import pandas as pd
import sys
sys.path.append("/nethome/tofhr/ollivier/IN5/experiments_management/SoftTools/Gantt_Calendars/gantt-schedule/")
# import src.libschedule as lg
import src.parse_userdispo as pu
from importlib import reload

In [13]:
planfile = "/home/ollivier/serhome/IN5/experiments_management/SoftTools/Gantt_Calendars/gantt-schedule/tests/data/userDispo_test.txt"
planfile = "/home/ollivier/Calendars/UsersDispo"  # <-- the usr dispo

In [25]:
reload(pu)
df = pu.parse_carefully(planfile, verbose=False, print_info=False)
df.tail()

        Experiment       User      Start      Finish  Duration Bool
540        YES:Pan        Pan 2026-10-17  2026-10-23         6  YES
541        NO:Bove       Bove 2026-10-18  2026-10-29        11   NO
542  YES:Rodriguez  Rodriguez 2026-10-20  2026-10-29         9  YES
543      YES:Seels      Seels 2026-10-23  2026-10-29         6  YES
544      YES:Weber      Weber 2026-10-26  2026-10-29         3  YES

In [23]:
df.head()

,Experiment,User,Start,Finish,Duration,Bool
0,NO:Brusselez,Brusselez,2008-11-01,2008-11-10,9,NO
1,NO:Judenstein/Zanotti,Judenstein/Zanotti,2008-11-01,2008-11-30,29,NO
2,NO:Brusselez,Brusselez,2008-11-17,2008-11-30,13,NO
3,NO:JOBIC,JOBIC,2008-12-05,2008-12-19,14,NO
4,NO:Brusselez,Brusselez,2008-12-08,2008-12-19,11,NO